name: Dispatch rebuild website and manuscript

on:
  workflow_dispatch:

jobs:
  build_website:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.CI_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install jupyter-book==1.0.4 ghp-import nbconvert

      - name: Build website and manuscript
        run: |
          # Build website
          rm -f pipeline/*.ipynb
          jupyter-book build .  --path-output . --config website/_config.yml --toc website/_toc.yml
          rsync -auzP code/images/* _build/html/_images/
          ghp-import -n -p -f _build/html

          # Link notebooks
          find code -name '*.ipynb' | grep -v "ipynb_checkpoints" | xargs -I % bash -c 'ln -s % pipeline/$(basename %)'

          # Make manuscript
          cd website/nature_protocol
          jupyter nbconvert --to notebook --execute conversion_notebook.ipynb && rm -f conversion_notebook.nbconvert.ipynb

      - name: Commit changes to pipeline
        uses: EndBug/add-and-commit@v9
        with:
          push: true
          message: Update pipeline
